version: "3.7"
services:
  app:
    build:
      args:
        user: avnadmin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: transcendtrade_img
    container_name: container_transcendtrade
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - transcendtrade.org
  db:
    image: mysql:8.0
    container_name: transcendtradeDB
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - transcendtrade.org
  nginx:
    image: nginx:alpine
    container_name: transcendtrade-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - transcendtrade.org
networks:
  transcendtrade.org:
    driver: bridge